### PR TITLE
webapp: migrate to sqlalchemy 2.0

### LINKED ISSUE #434: Migrate to SQLAlchemy 2.0
Once SQLAlchemy 2.0 comes out, remove the ceiling imposed in https://github.com/conbench/conbench/pull/433 and fix any broken tests.

### PR DESCRIPTION
**Pull request by austin3dickey**
Closes #434.

### CODE REVIEW

**Comment by austin3dickey** [comment]
This build installed `SQLAlchemy-2.0.5.post1` and all tests succeeded. I'll try to set up a local app connected to the Arrow database, play around with it, and see if anything breaks.

**Comment by jgehrcke** [comment]
This pretty much looks like we can already land this! :) Any risks that we can think of if we were to leave it in this state?

**Comment by austin3dickey** [comment]
I think I'll strip out the debugging environment variables from the test suite again.

**Comment by austin3dickey** [comment]
Will merge after tests succeed.

**Comment by austin3dickey** [comment]
This successfully deployed to our internal staging conbench instance and it seems healthy!

**Review by jgehrcke — COMMENTED** [review]
:rocket: nice

**Comment by austin3dickey** [comment]
This is really impressive already. For example, the `.search()` method of our internal DB entities is not type hinted yet. But VS Code can now inspect that method (with SQLAlchemy 2.0) and figure out that it returns a list of instances of that entity. Really cool stuff.

Screenshot 2023-03-13 at 12 12 06

https://github.com/conbench/conbench/blob/5e626d479ed38ef53e02d102f084df4387f331eb/conbench/entities/_entity.py#L45-L53

**Pull request merged**
