### PR TITLE
webapp: gzip-compress HTTP responses (issue #1140)

### PR DESCRIPTION
**Pull request by jgehrcke**
This works:

```
$ curl -sH 'Accept-encoding: gzip' localhost:5000 | gunzip - | head -n3
<!DOCTYPE html>
  <html lang="en">
      <head>
```

```
 $ curl -sH 'Accept-encoding: gzip' localhost:5000/api/benchmarks/ | gunzip - | head -n3
[
  {
    "id": "0644107c9f5f79bf800082e0cb94fe12",
```

### CODE REVIEW

**Comment by jgehrcke** [comment]
The check-docs check is a tiny bit impactul every now and then.
```
WARNING: autodoc: failed to import module 'runner' from module 'conbench'; the following exception was raised:
No module named 'flask_compress'
```

**Comment by jgehrcke** [comment]
Let's get this in! :rocket:

**Comment by austin3dickey** [comment]
>The check-docs check is a tiny bit impactul every now and then.

This was a legitimate problem, though, right? The reason the build failed is that: 
- during the docs build, we `pip install .` (the `conbench` library/CLI for the legacy runner) with no extras, just like the [Arrow Benchmark CI](https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/118389b7e367dd2318e2d0a399d20350466f298b/buildkite/benchmark/utils.sh#L76) does
- when building the docs, we tried to `import conbench.runner`, and failed because we didn't have a required dependency

This means that if we had merged the PR as of the failing build, and Arrow updated its peg to use that version of the CLI, then Arrow Benchmark CI would have been broken too.

You moved the import inside the function, which is fine! But another solution would have been to add `Flask-Compress` to `requirements-cli.txt` instead of `requirements-webapp.txt`, because adding a dependency to the top of `conbench.__init__.py` is making it a dependency of the CLI too, not just the webapp.

This of course relates to https://github.com/conbench/conbench/issues/617, and also https://github.com/conbench/conbench/issues/618 (because if we tested `conbench.runner` better, we wouldn't have to rely on the `check-docs` step to catch this type of thing), and it also points a finger toward the removal of the legacy CLI sooner than later. 🙂

**Comment by jgehrcke** [comment]
Thanks for looking at this, Austin! 

> This was a legitimate problem, though, right? 

Oh, jeeeeez. Yes. I didn't look deep enough to see that it's _that_ kind of problem space.

We need to tackle this. I take "The check-docs check is a tiny bit impactul every now and then." back, it in fact has just its own way of reminding us of the dead bodies in the cellar, and I didn't connect the dots.

All the more reason to deal with the "legacy CLI" challenge.

> Arrow updated its peg to use that version of the CLI, then Arrow Benchmark CI would have been broken too.

Over there we do have this pinned in the meantime, right?

>  would have been to add Flask-Compress to requirements-cli.txt

Of course that's technically true! I hope we both feel the pain about the misleading semantics of this :P

I have the suspicion that in the meantime we have added dependencies to -webapp and not -cli.

**Comment by austin3dickey** [comment]
>Over there we do have this pinned in the meantime, right?

Yes, it's pinned: 
https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/118389b7e367dd2318e2d0a399d20350466f298b/buildkite/benchmark/utils.sh#L76

>I have the suspicion that in the meantime we have added dependencies to -webapp and not -cli.

This is probably true, but the docs-check probably failed whenever we did, which caused us to move those deps inside webapp functions :) luckily at least with the current state of docs-check we know that `conbench.runner` is importable without `requirements-webapp`, because `autodoc` needs to import it to build docs. But yes, this is not ideal.

**Pull request merged**
