### PR TITLE
ci: add curlylint and djlint for Jinja2/HTML, resolve a variety of lint errors

### LINKED ISSUE #1120: ci: add linting for jinja2 HTML templates
I don't love Jinja2 at this point, but it's what we have and continue to use for now. 

The combination of Python, Jinja2, HTML is not the most amazing in terms of developer productivity, with limited IDE support in the template files themselves, see for instance https://github.com/microsoft/pylance-release/discussions/4090.

However, some of our templates might result in invalid HTML. I have done basic checking here and there (also see https://github.com/conbench/conbench/issues/836).

For example, here are two opening tables, and only one closing: https://github.com/conbench/conbench/blob/377dc55bedccaa60b7d217d3c657a750de4ffbf2/conbench/templates/benchmark-list.html#L16

Let's introduce

- https://www.curlylint.org/  / https://github.com/thibaudcolas/curlylint
- https://www.djlint.com/ / https://github.com/Riverside-Healthcare/djlint

It's great that these projects exist at all, somehow they feel like niche and not too established.

Cute summary:

> Once upon a time all the other programming languages had a formatter and linter. [...]. The cool kids on the block. HTML templates were left out there on their own, in the cold, unformatted and unlinted :( The dirty corner in your repository. Something had to change.

Also interesting: https://github.com/rtts/djhtml, with its focus on JavaScript, CSS.

### PR DESCRIPTION
**Pull request by jgehrcke**
This resolves https://github.com/conbench/conbench/issues/1120, and is also a decent leap towards https://github.com/conbench/conbench/issues/836.

It's just a starting point though, I think we have to tune some decisions on-the-fly.

I see that this creates merge conflicts with https://github.com/conbench/conbench/pull/1114, but they are rather small; I hope adjusting only takes a few minutes of your time @alistaire47; let me know if I can/should help.

Docs:
- https://djlint.com/docs/linter/
- https://www.curlylint.org/

Still need to figure out if https://github.com/rtts/djhtml can / should also be used.

See commit messages to get am impression about how I approached this: reformat, fix, reformat, fix -- some errors needed "reformatting" and also fixing before more problems could be detected.

Some resources that can help explain some of the commits:
https://github.com/thibaudcolas/curlylint/issues/14
https://github.com/thibaudcolas/curlylint/pull/53
https://github.com/thibaudcolas/curlylint/issues/22
https://github.com/thibaudcolas/curlylint/issues/6
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current
https://stackoverflow.com/questions/11928566/img-vs-image-tag-in-html
https://stackoverflow.com/questions/13232121/closing-html-input-tag-issue

Other solutions I looked at: https://github.com/motet-a/jinjalint seems to be outdated, https://github.com/aristanetworks/j2lint is too underground, https://github.com/drm/jinja2-lint is :shrug:  -- I just made some quick decisions here, maybe we want to re-look at those last three.

I have added the new commands to `make lint`, maybe we want to have a separate target for this in the future; we will see.

### CODE REVIEW

**Comment by jgehrcke** [comment]
From CI:

```
curlylint conbench/templates/
All done! ✨ 🍰 ✨

djlint . --extension=html.j2 --check --indent=2 conbench/templates/*html


Checking 0/19 files ┈┈┈┈┈┈┈┈┈┈ 00:00    
Checking 1/19 files ┈┈┈┈┈┈┈┈┈┈ 00:00    
[...]
Checking 19/19 files ━━━━━━━━━━ 00:04    


0 files would be updated.
```

**Comment by jgehrcke** [comment]
Btw, when I started with curlylint I got errors like this:
```
± curlylint conbench/templates/
conbench/templates/batch.html
26:11	Parse error: expected one of 'autoescape', 'block', 'blocktrans', 'comment', 'endif', 'filter', 'for', 'if', 'ifchanged', 'ifequal', 'ifnotequal', 'not an intermediate Jinja tag name', 'spaceless', 'verbatim', 'with' at 26:11	parse_error

conbench/templates/benchmark-list.html
48:51	Parse error: expected 'attribute value' at 48:51	parse_error

conbench/templates/benchmark-result.html
12:52	Parse error: expected one of '>', 'space(s) between attributes', '{#', '{%', '{{' at 12:52	parse_error

conbench/templates/compare-entity.html
8:9	Parse error: expected one of 'autoescape', 'block', 'blocktrans', 'comment', 'endif', 'filter', 'for', 'if', 'ifchanged', 'ifequal', 'ifnotequal', 'not an intermediate Jinja tag name', 'spaceless', 'verbatim', 'with' at 8:9	parse_error

conbench/templates/compare-list.html
58:11	Parse error: expected one of 'autoescape', 'block', 'blocktrans', 'comment', 'endif', 'filter', 'for', 'if', 'ifchanged', 'ifequal', 'ifnotequal', 'not an intermediate Jinja tag name', 'spaceless', 'verbatim', 'with' at 58:11	parse_error

conbench/templates/run.html
40:11	Parse error: expected one of 'autoescape', 'block', 'blocktrans', 'comment', 'endif', 'filter', 'for', 'if', 'ifchanged', 'ifequal', 'ifnotequal', 'not an intermediate Jinja tag name', 'spaceless', 'verbatim', 'with' at 40:11	parse_error

conbench/templates/units-tooltip.html
0:93	Parse error: expected 'attribute value' at 0:93	parse_error

conbench/templates/user-list.html
45:42	Parse error: expected 'attribute value' at 45:42	parse_error

Oh no! 💥 💔 💥
8 errors reported
```
They read cryptically, yes. But each one of those led to an HTML output problem. I kind of started to 'hate' these error messages, but after investigation I found that it's better to have _those_ (weird) hints, than to have none.

For now, all these have been repaired.

**Comment by jgehrcke** [comment]
Going ahead with this :ship:

**Comment by austin3dickey** [comment]
Thank you! This looks fantastic!

**Pull request merged**
