### PR TITLE
Improve lscpu parsing (#337)

### PR DESCRIPTION
**Pull request by n3world**

### CODE REVIEW

**Comment by ElenaHenderson** [comment]
Hello @n3world, happy to see a new contributor. Please let me and @dianaclarke know when you need a review.

**Comment by dianaclarke** [comment]
Thanks for the pull request, @n3world!

It's been a while since I worked in this code, but I think it currently tries to get the `cpu_model_name` in the following order:

- `sysctl -n machdep.cpu.brand_string`
- `brand_raw` from lib `cpuinfo`

If I've understood correctly, this change looks in this order instead:

- `sysctl -n machdep.cpu.brand_string`
- `Model name` from `lscpu --bytes`
- `brand_raw` from lib `cpuinfo`

So the new `lscpu` lookup will only be hit if `sysctl -n machdep.cpu.brand_string` fails to find a value. Is that what you're seeing?

Out of curiosity, are you running a Conbench server? I don't know of other Conbench servers in the wild (aside from Arrow and Voltron), so that would be exciting news! 😄 

Have a great weekend!

**Comment by n3world** [comment]
> So the new `lscpu` lookup will only be hit if `sysctl -n machdep.cpu.brand_string` fails to find a value. Is that what you're seeing?

Yes that should be the case.

It appears that on my Linux machines cpuinfo just prints the same values as lscpu and because of the lscpu output changes the cpuinfo parsing does not work either. For example this is what I see locally for cpuinfo output

```
{
...
 'l1_data_cache_size': '192 KiB (6 instances)',
 'l1_instruction_cache_size': '192 KiB (6 instances)',
 'l2_cache_associativity': 6,
 'l2_cache_line_size': 256,
 'l2_cache_size': '1.5 MiB (6 instances)',
 'l3_cache_size': 9437184,
...
}
```

Not sure how consistent/reliable cpuinfo output is across operating systems since I only have access to Linux but it seems like that might need some work too. A simple change to machine_info.py:247-248 to handle the first element as `value` the second as `unit` and ignore the rest could fix it but not sure if that would cause issues in other environments.


```
--- a/conbench/machine_info.py
+++ b/conbench/machine_info.py
@@ -240,11 +240,11 @@ def _fill_from_cpuinfo(info, cpu_info):
                     info[key] = cpu_info[lookup]
                 else:
                     value = str(cpu_info[lookup])
-                    parts = value.split(" ")
+                    parts = value.split(" ", maxsplit=2)
                     if len(parts) == 1:
                         info[key] = int(float(value))
-                    elif len(parts) == 2:
-                        value, unit = parts
+                    elif len(parts) >= 2:
+                        value, unit = parts[:2]
                         value = int(float(value))
                         if unit == "KiB":
                             info[key] = value * 1024
```

> Out of curiosity, are you running a Conbench server? I don't know of other Conbench servers in the wild (aside from Arrow and Voltron), so that would be exciting news! smile

Yes we have one running to test out sending benchmark results to.

**Comment by dianaclarke** [comment]
I see now, thanks!

I was confused because this PR does 2 things (that's not on you, it's just been a long day at DAY_JOB):
- Adds getting `Model name` from `lscpu`
- Handles parsing ints from `lscpu` that look like `"L2 cache:                        16777216 (6 instances)"`

Can you please update the test like this, so this parsing is exercised? Assuming that's close to what you're seeing?

```
diff --git a/conbench/tests/benchmark/test_machine_info.py b/conbench/tests/benchmark/test_machine_info.py
index 99a4685..8fa0a9b 100644
--- a/conbench/tests/benchmark/test_machine_info.py
+++ b/conbench/tests/benchmark/test_machine_info.py
@@ -36,7 +36,7 @@ LSCPU = [
     "Virtualization:                  VT-x",
     "L1d cache:                       524288",
     "L1i cache:                       524288",
-    "L2 cache:                        16777216",
+    "L2 cache:                        16777216 (6 instances)",
     "L3 cache:                        23068672",
     "NUMA node0 CPU(s):               0-31",
     "Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled",
```

There is a risk that the `Model name` from `lscpu --bytes` might differ from what it found before using `cpuinfo`. If it returns a different value, then it won't match historic machine definitions, and new benchmarks might fail to find their historical comparisons.

It would be less risky to just include the int parsing change in this pull request.  How confident are you that `lscpu's` `Model name` won't differ from `cpuinfo's` `brand_raw` ? I honestly don't know. 

Thanks again!

PS. I don't actively work on Conbench anymore, but I'm super thrilled to see someone using it. Are you open to saying where you work? No, is totally fine. Cheers! 🍻

**Comment by dianaclarke** [comment]
Oh! We might have another issue. Conbench assumes the cache sizes are listed in bytes. If you're seeing `MiB` from both `cpuinfo` and `lscpu` we'll need unit conversion too.

- `'l2_cache_size': '1.5 MiB (6 instances)'`

**Comment by dianaclarke** [comment]
Hmmm.... That said, my bad, you shouldn't get results in MiB given Conbench uses `lscpu --bytes`. So sorry for the noise. Long week at DAY_JOB. Can you show me what `lscpu --bytes` outputs for you? We're close to merging this. Much appreciated!

**Comment by n3world** [comment]
Sorry for the delay.
> How confident are you that lscpu's Model name won't differ from cpuinfo's brand_raw ? I honestly don't know.

I am fairly confident they are the same but not 100%. Looking at cpuinfo source it looks like it tries to get the value from a few places including /proc/cpuinfo and lscpu and the string returned by those tools is the model string which the cpu itself reports. If this is a significant concert for you I can remove that change.
> Are you open to saying where you work?

I work at Einblick Analytics. 
> Conbench assumes the cache sizes are listed in bytes. If you're seeing MiB from both cpuinfo and lscpu we'll need unit conversion too

The size in MiB only comes from cpuinfo but that is handled by the cpuinfo parser.
Do you want me to try and fix cpuinfo parsing to also handle the extra info?
> Can you show me what lscpu --bytes outputs for you?

This is my full lscpu output
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
CPU family:                      6
Model:                           158
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        10
CPU max MHz:                     4100.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4399.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust sgx bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp sgx_lc md_clear flush_l1d
Virtualization:                  VT-x
L1d cache:                       196608 (6 instances)
L1i cache:                       196608 (6 instances)
L2 cache:                        1572864 (6 instances)
L3 cache:                        9437184 (1 instance)
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Vulnerable: No microcode
Vulnerability Tsx async abort:   Not affected
```

**Review by dianaclarke — APPROVED** [review]
LGTM! Thanks so much for the pull request and digging into library source wrt the model name.

I would like to see this diff applied to the tests, so that this new code path is exercised, but I can follow up in a subsequent pull request.

```
diff --git a/conbench/tests/benchmark/test_machine_info.py b/conbench/tests/benchmark/test_machine_info.py
index 99a4685..8fa0a9b 100644
--- a/conbench/tests/benchmark/test_machine_info.py
+++ b/conbench/tests/benchmark/test_machine_info.py
@@ -36,7 +36,7 @@ LSCPU = [
     "Virtualization:                  VT-x",
     "L1d cache:                       524288",
     "L1i cache:                       524288",
-    "L2 cache:                        16777216",
+    "L2 cache:                        16777216 (6 instances)",
     "L3 cache:                        23068672",
     "NUMA node0 CPU(s):               0-31",
     "Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled",
```

@ElenaHenderson I'll let you merge this, as you're the one that will have to address any fallout (which I don't anticipate, but there's a very small chance). When you merge this, watch a few runs and make sure the machine definitions haven't changed. Thanks all!

**Pull request merged**
