### PR TITLE
Speed up set_z_scores()

### PR DESCRIPTION
**Pull request by austin3dickey**
This PR speeds up `set_z_scores()` by using a better data structure. When there are many `benchmark_results`, each one was searching through the entire distribution query to find the 0 or 1 matches for its case/context, and that took a long time. We should have been using a hash lookup for this.

Helps with #599.

### CODE REVIEW

**Comment by jonkeane** [comment]
We don't need to do this now (and it would be good to get this out quicker than later), but we _should_ make a benchmark for this (+ setup conbench on conbench to track it!) so that we don't accidentally revert this in the future. Would you mind making a separate issue (or issues) for that?

**Comment by jgehrcke** [comment]
Cool! Really lovely analysis in https://github.com/conbench/conbench/issues/599#issuecomment-1387672510. Great work. I trust that this is a great algorithmic improvement (did not review the details). Let's land this.

So, we call `set_z_scores()` when GETting `compare/runs/<x>...<y>`, yes? It's a very important observation (architectural smell :-)). Relates to https://github.com/conbench/conbench/issues/577.

> We don't need to do this now (and it would be good to get this out quicker than later), but we should make a benchmark for this (+ setup conbench on conbench to track it!) so that we don't accidentally revert this in the future. 

Related to this: request duration measurements and alerts via observability for actual deployments: https://github.com/conbench/conbench/issues/493

**Review by jgehrcke — APPROVED** [review]
:rocket:

**Comment by austin3dickey** [comment]
>We don't need to do this now (and it would be good to get this out quicker than later), but we should make a benchmark for this (+ setup conbench on conbench to track it!) so that we don't accidentally revert this in the future. Would you mind making a separate issue (or issues) for that?

Yes, good idea. I had mentioned this thought earlier in #493 but it belongs its own ticket. I just created #606.

**Pull request merged**
